const zodiacSigns = [
    'Aries',
    'Taurus',
    'Gemini',
    'Cancer',
    'Leo',
    'Virgo',
    'Libra',
    'Scorpio',
    'Sagittarius',
    'Capricorn',
    'Aquarius',
    'Pisces',
]
const PASSIONS = [
    'Harry Potter',
    'Spa',
    'Camping',
    'Cars',
    'Anime',
    'TikTok',
    'Fashion',
    'Boba Tea',
    'Comedy',
    'Netflix',
    'Samba',
    'Boxing',
    'Twitch',
    'Outdoors',
    'MLB',
    'Fishing',
    'Gym',
    'Street Food',
    'Baking',
    'Clubbing',
    'Swimming',
    'Yoga',
    'Theatre',
    'Hip Hop',
    'Poetry',
    'Reading',
    'Self Care',
    'Sushi'
]